### ISSUE TITLE
基于 Starcoder-15B 的 CODEM-Mixed 

### ISSUE THREAD

**Issue by DBM1** [NL2Code/CodeM#2]
请问是否尝试过使用 Starcoder-15B 训练 CODEM-Mixed？如果表 1 的结论可以推广，那么这种方法应该比 CODEM-Python 有更好的性能。

**Comment by NL2Code** [comment]
您好，感谢关注我们的工作。

根据在StarCoder 7B上的实验，多语言的设置（CodeM-Mixed）在每个语言上都表现最优或者次优，所以我们猜测基于StarCoder-15B的CodeM-Mixed在HumanEval-Python也会和CodeM-Python保持附近持平甚至超过现在的性能（pass@1/acc = 64.63）。

祝好
